Siren Event Overhaul
Occulus-Server/Occulus-Eris pull request #1018
Opened 2023-06-14 20:45 UTC by RadiantFlash7

## About The Pull Request
overhauls the Siren event in the various ways:

- Siren AI completely overhauled. It is now superior in most ways, and will retarget to hostiles closer to itself. it also will prevent Z level cheesing.
- Fixes Siren spawning too close with an additional check in spawn formula.
- moves siren event to /major/ ups crew requirement to 15, or 11 with significant reduced chance of activation.
- adds custom siren explosion proc to halve the damage recieved from augmentor explosions.
- lengths augmentor fire rate a bit further.
- adds in a siren boss mob,the Nemesis Assault Strider that /can/ trigger when there is 17 or more crew members on the ship.
- Siren boss mob features several differant(4) attack phases.
- siren mobs in general have recieved a bit less damage from rubber rounds. Provides a time to break out lethals, and given the time and warning the crew recieves, this should be relatively reasonable.
- conservator laser agony reduced.
- some siren mobs have an accuracy modifier now, providing a chance for shots to deviate 15 degrees.
- This PR will add an additional 3-4 siren mobs(A turret, nanite swarm, a robot with an AOE, and a miniboss) once feature complete.

## Why It's Good For The Game

## Changelog
```changelog
add: 4-5 new siren mobs
add: Siren Boss Mob
add: Siren ranged weapon inaccuracy
tweak: rewrote the AI code for siren mobs
tweak: Siren is now a major event
tweak: Siren events danger level now scales /somewhat/ based on player count a bit better.
balance: Siren mobs less damaged by rubbers
balance: damage done by augmentor explosions halved
balance: conservator laser agony reduced.
fix: siren spawns no longer spawn too close to people.
soundadd: added 3 new sounds for a siren mob
```

2023-06-14 20:48 UTC, RadiantFlash7 commented
Not ready yet... Pls do not look through till ready 😸

2023-06-17 20:26 UTC, RadiantFlash7 commented
Ready for review. At present, only one mob is not yet functioning 100% as intended. The Intruder's lightning AOE seems to not be providing it's 'beam' lightning sprite.

2023-06-18 03:50 UTC, RadiantFlash7 commented
I can't get the shockloop to work , but honestly it's a feature that can be added at a later date. The PR is ready to merge at this point. Pls review 😸

2023-06-18 16:51 UTC, fludd12 requested changes
I did a more cursory review than I normally do, since I was there to watch a lot of the testing! That said, there's some code cleanup that needs to be done with booleans for readability.

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/intruder.dm
> +	ranged = 1
Based on elsewhere, this seems to be meant as a boolean. Use TRUE for 1 and FALSE for 0

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/nemesis.dm
> +	ranged = 1
See previous comment.

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/nemesis.dm
> +			ranged = 1
```suggestion
		if(!ranged)
			ranged = TRUE
```

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/nemesis.dm
> +			ranged = 0
```suggestion
		if(ranged)
			ranged = FALSE
```

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	ranged = 1
`ranged = TRUE`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +		ranged = 1
`ranged = TRUE`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +		ranged = 0
`ranged = FALSE`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/turret.dm
> +	ranged = TRUE
oh hey you read my mind, here 😛

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	var/transcended = 0
Similarly seems to be a boolean value. `transcended = FALSE`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	if(transcended == 0 && world.time >= transcend_change_time)
`if(!transcended && //etc`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	transcended = 1
`transcended = TRUE`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	transcended = 0
`transcended = FALSE`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	if(transcended == 1)
`if(transcended)`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	if(transcended == 1)
`if(transcended)`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	if(transcended == 1)
`if(transcended)` a bunch of times!

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/siren.dm
> +	destroy_surroundings = 1
`= TRUE`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/turret.dm
> +		targetting = 1
`targetting = TRUE`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/turret.dm
> +	var/targetting = 0
`targetting = FALSE`
(also, it'd be _targeting_, but that's not important - there's plenty of awkward spellings throughout the code.)

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/turret.dm
> +		if(targetting == 1)
`if(targetting)`

2023-06-18 16:51 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/turret.dm
> +		targetting = 0
`targetting = FALSE`

2023-06-18 18:55 UTC, RadiantFlash7 commented
Requested Boolean changes made!

2023-06-19 18:25 UTC, RadiantFlash7 commented
Adjusted the balance a bit.
Removed an extraneous file as shock ability for intruder has been replaced.

2023-06-19 18:48 UTC, fludd12 requested changes
Just a few more changes, sorry!

2023-06-19 18:48 UTC, fludd12 commented on zzzz_modular_occulus/code/game/gamemodes/events/siren_scan.dm
> +	tags = list(TAG_SCARY, TAG_COMMUNAL, TAG_COMBAT, TAG_NEGATIVE,)
Trailing comma!

2023-06-19 18:48 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	var/transcended = 0
Unaddressed

2023-06-19 18:48 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	if(transcended == 0 && world.time >= transcend_change_time)
Unaddressed

2023-06-19 18:48 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	transcended = 1
Unaddressed

2023-06-19 18:48 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	transcended = 0
Unaddressed

2023-06-19 18:48 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	if(transcended == 1)
Unaddressed

2023-06-19 18:48 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	if(transcended == 1)
Unaddressed

2023-06-19 18:48 UTC, fludd12 commented on zzzz_modular_occulus/code/modules/mob/living/simple_animal/hostile/siren/oracle.dm
> +	if(transcended == 1)
Unaddressed

2023-06-19 22:03 UTC, RadiantFlash7 commented on zzzz_modular_occulus/code/game/gamemodes/events/siren_scan.dm
> +	tags = list(TAG_SCARY, TAG_COMMUNAL, TAG_COMBAT, TAG_NEGATIVE,)
Trailing comma removed,

2023-06-19 22:04 UTC, RadiantFlash7 commented
Whoops, All boolean.
Fixed up!

2023-06-20 04:36 UTC, fludd12 approved these changes
Looks good to me!

2023-06-20 15:56 UTC, merged