fixes .60 scrap box from spawning hellishly often
Occulus-Server/Occulus-Eris pull request #204
Opened 2021-02-03 10:27 UTC by bearrrrrrrr

## About The Pull Request

blacklists .60 boxes from spawning. why were they allowed to spawn???? why was their rarity value 1???????? LMAO

## Why It's Good For The Game

https://media.discordapp.net/attachments/777382113737572393/806331599146582074/unknown.png

## Changelog
```changelog
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
```

2021-02-03 10:30 UTC, cebutris commented
https://github.com/discordia-space/CEV-Eris/pull/5897

2021-02-03 10:30 UTC, bearrrrrrrr commented
> [discordia-space/CEV-Eris#5897](https://github.com/discordia-space/CEV-Eris/pull/5897)

already ported that. didn't work. assuming direct control.

2021-02-04 11:16 UTC, Jamini requested changes
Bear, please mark the non-modular changes or make a modular changefile.

Aside from that.. approved!

2021-02-04 11:25 UTC, bearrrrrrrr commented
O O O P S

2021-02-04 11:27 UTC, Jamini approved these changes

2021-02-04 11:27 UTC, Jamini commented
:blobcatpet:

2021-02-04 15:16 UTC, Michiyamenotehifunana commented
Do not merge until we confirm that https://github.com/Occulus-Server/Occulus-Eris/pull/210 fixes this.

2021-02-08 03:49 UTC, bearrrrrrrr commented
closing since not needed, fixed as of loot rework

2021-02-08 03:49 UTC, closed without merging