Adds autodoc machine
Occulus-Server/Occulus-Eris pull request #246
Opened 2021-02-11 17:24 UTC by Jamini

## About The Pull Request

This PR re-enables and fixes the autodoc machinery in code

## Why It's Good For The Game

Adds a stationary autodoc in medical for lowpop rounds. The procedures are fairly expensive and quite slow, so it's difficult for anyone to simply spam. But in a pinch it can save you from certain death via a broken rib or the like. 

## Changelog
```changelog
add: stationary autodoc in medical
```

2021-02-11 17:29 UTC, Jamini commented
![image](https://user-images.githubusercontent.com/1775680/107674249-c73b1700-6c64-11eb-99b7-68779fa729d4.png)

2021-02-11 19:37 UTC, Jamini commented
![image](https://user-images.githubusercontent.com/1775680/107689279-9fed4580-6c76-11eb-8423-e49bfb0002a7.png)

2021-02-13 15:52 UTC, Jamini commented
After a GREAT DEAL of circular discussion, this passed emojicracy.

2021-02-13 16:45 UTC, zackerycodestoo commented
Entering the Autodoc as an FBP causes a runtime and makes the machine lock up after scanning your ID (runtime not present on an organic entering, I deleted and respawned the autodoc before doing so):

![image](https://user-images.githubusercontent.com/77511162/107855424-3bee8c80-6df0-11eb-9774-574c2f004f94.png)
![image](https://user-images.githubusercontent.com/77511162/107855429-46a92180-6df0-11eb-8bd4-8441f0af2e5a.png)

(The second image is a continuation of the first, the second image starts at the first's final line)

2021-02-13 16:46 UTC, zackerycodestoo requested changes
Entering the Autodoc as an FBP causes a runtime and makes the machine lock up after scanning your ID (runtime not present on an organic entering, I deleted and respawned the autodoc before doing so):

![image](https://user-images.githubusercontent.com/77511162/107855424-3bee8c80-6df0-11eb-9774-574c2f004f94.png)
![image](https://user-images.githubusercontent.com/77511162/107855429-46a92180-6df0-11eb-8bd4-8441f0af2e5a.png)

(The second image is a continuation of the first, the second image starts at the first's final line)

2021-02-13 16:49 UTC, zackerycodestoo requested changes
The area is marked as 'Psych Room' on GPS -- could that be adjusted to 'Autodoc Room'?

2021-02-13 16:52 UTC, zackerycodestoo reviewed
Non-blocking comment: The Psychiatrist spawns in the Medical Isolator now, could that be moved to the Break Room?

Also, I understand that shrapnel removal is bugged -- I might suggest looking at the shrapnel removal code at code/modules/surgery/organic.dm, lines 410-417 -- the primary difference I see in the code here is that organic.dm refers to organs as _/obj/item/organ/external_ while the autodoc code is checking _/obj/item/organ/internal_

2021-02-14 09:07 UTC, Jamini commented
> Entering the Autodoc as an FBP causes a runtime and makes the machine lock up after scanning your ID (runtime not present on an organic entering, I deleted and respawned the autodoc before doing so):
> 
> ![image](https://user-images.githubusercontent.com/77511162/107855424-3bee8c80-6df0-11eb-9774-574c2f004f94.png)
> ![image](https://user-images.githubusercontent.com/77511162/107855429-46a92180-6df0-11eb-8bd4-8441f0af2e5a.png)
> 
> (The second image is a continuation of the first, the second image starts at the first's final line)
> 
> I know that FBPs shouldn't be able to use it but I'm a wild animal and wanted to see what would happen

The exact same thing probably would occur if a FBP tried to use an autodoc module on a hardsuit. It should be possible to clear this by leaving the autodoc (since when that occurs the old autodoc datum is deleted and a new one is created)

I'll move the psych spawn in the morning.

2021-02-14 09:09 UTC, zackerycodestoo commented
It did not clear the autodoc when I left it -- the runtime kept continuing every time I entered it after it scanned my ID (including possessing a normal human mob and entering it while it was in the lock-up state). The only way I was able to clear it was by deleting the autodoc and spawning a new machine

2021-02-14 16:06 UTC, Jamini commented
![image](https://user-images.githubusercontent.com/1775680/107881949-bbde2a80-6eb4-11eb-950a-5bb1eef465fb.png)

Could not reproduce the FBP thing.

2021-02-14 16:14 UTC, Jamini commented
Completely unable to reproduce

![image](https://user-images.githubusercontent.com/1775680/107882154-c4833080-6eb5-11eb-9fdb-893f16477b7a.png)

2021-02-14 19:30 UTC, zackerycodestoo approved these changes

2021-02-16 00:41 UTC, merged