ports from Eris, again
Occulus-Server/Occulus-Eris pull request #255
Opened 2021-02-14 07:11 UTC by bearrrrrrrr

## About The Pull Request

Eris ports.
https://github.com/discordia-space/CEV-Eris/pull/5905
https://github.com/discordia-space/CEV-Eris/pull/5890

## Why It's Good For The Game

Free content.

## Changelog
```changelog
add: Club worker and Mekhane people have new traits. New litany for agrolyte. 
```

2021-02-14 07:16 UTC, bearrrrrrrr commented
don't merge/review just yet pls, committed early like a dingus-

2021-02-14 07:28 UTC, bearrrrrrrr commented
good to go. seemed to run/work fine when i tested it but someone PLEASE look this over, i am terrified of spaghetti removed/readded/rebalanced/partially-modularized cruciform code

2021-02-14 18:13 UTC, Jamini commented
Please write what is added changed in detail, using the PR format Bear.

2021-02-14 22:24 UTC, bearrrrrrrr commented
oki

2021-02-15 18:59 UTC, zackerycodestoo requested changes
Bear, would you please look and see if Eris upstream has further pulls related to these? Here is what I found out:

1. The Club perk doesn't actually seem to have an effect, since the sanity gain rate of a low-sanity was unchanged while I was near them with the perk
2. The Custodian perk is significantly underwhelming and does not trigger on spray bottles, cleaner grenades, or broad sweeps of the mop -- only on single-target cleaning, and _also_ can be triggered by cleaning the same clean tile repeatedly

The Agrolyte perks and ritual at least seem to work as expected.

Other notes I made and confirmed:

1. /obj/item/device/scanner and its children still work as expected
2. The Agrolyte examine still gets 'print report' and 'clear data', but those buttons don't do anything, so it's fine
3. Plants still grow without boosted growth (I was mighty suspicious of this one)

2021-02-15 18:59 UTC, zackerycodestoo commented on code/game/turfs/simulated/cleaning.dm
> +				H.sanity.changeLevel(0.5)
This code is flawed -- it doesn't activate when using cleaner spray, cleaner grenades, or even broad sweeps of mops, but only when you clean a single tile at a time (single-tile mopping, soap, wet rags, etc) and will likely significantly underwhelm any players expecting it to be a good source of sanity regain

2021-02-15 18:59 UTC, zackerycodestoo commented on code/game/turfs/simulated/cleaning.dm
> +				H.sanity.changeLevel(0.5)
Additionally, it still triggers even if there's nothing to clean, so a custodian could theoretically spam their mop all over a clean floor to get their sanity back

2021-02-15 18:59 UTC, zackerycodestoo commented on code/datums/perks/job.dm
> +/datum/perk/job/club
Perk appears non-functional -- I didn't see any change in a low-sanity mob's sanity gain rate from standing near it while holding this perk, both nearby and far away, besides the normal gain rate

2021-02-15 21:27 UTC, bearrrrrrrr commented
I specifically double- and triple- checked, there are no fixes available with these changes. Up to yall if you don't want to get the new traits since they're sorta buggy or just want the new litany or want to close this entirely.

2021-02-16 01:00 UTC, zackerycodestoo commented
I do like the Agrolyte changes -- I would say to drop 5890 (Club Worker aura) from this pull and I can try to help you drop the Neat perk. The only reason I say to drop them is that it would cause folks to think they're a lot more effective than they actually are (and in the Club Worker perk's case, it doesn't work at all)

2021-02-16 22:33 UTC, bearrrrrrrr commented
Sure, can-do.

2021-02-16 22:37 UTC, bearrrrrrrr commented
These changes good? Removes club perk, clarifies Filthy perk. Tell me if you want the jannie one removed entirely.

2021-02-17 00:45 UTC, zackerycodestoo approved these changes
Thanks! It's fine to merge now that the text has been clarified

2021-02-17 09:06 UTC, merged