Adjusted some chems that were failing to process
Occulus-Server/Occulus-Eris pull request #284
Opened 2021-02-24 05:54 UTC by Jamini

## About The Pull Request

Adjusted some chems that were failing to process

## Why It's Good For The Game

Bugfix for some chems failing to process right

## Changelog
```changelog
fix: Spacaecillin, Toxins, and Synaptizine should now process correctly. Adjusted metabolism rate to REM * 0.25 from REM * 0.05
```

2021-02-24 21:22 UTC, zackerycodestoo commented
May fix #257, pending testing

For posterity, can you explain why this fixes metabolism? I know you posted it in Discord but someone may look back on this pull in the future. Non-blocking

2021-02-24 22:06 UTC, zackerycodestoo requested changes
Could you also extend this metabolism fix to paracetamol? During my testing of #257 I noticed sergal-bases were metabolizing chemicals with the exception of paracetamol (metabolism rate too low?) though I also noticed it with human bases as well. 15u paracetamol metabolized very slowly but 5u just sat there

2021-02-25 07:26 UTC, Jamini commented
All painkillers had their metabolism rate set to 0.02. I set it to REM * 0.25 like the others ( 0.05)

2021-02-26 00:18 UTC, zackerycodestoo approved these changes

2021-02-26 00:21 UTC, merged