Jamini matchpatch
Occulus-Server/Occulus-Eris pull request #315
Opened 2021-03-06 13:23 UTC by Jamini

## About The Pull Request

Adds platinum to maint loot drop pools and broken autolathes

## Why It's Good For The Game

Adds a source of rare materials for high-end batteries to maint.

## Changelog
```changelog
balance: Added some platinum to maint spawns
```

2021-03-06 14:02 UTC, zackerycodestoo submitted a review, later dismissed
There are times when I've been craving borosilicate glass. Thank you

2021-03-07 00:07 UTC, Michiyamenotehifunana requested changes
REEEEEE science shouldn't spawn with phoron glass.

2021-03-07 00:07 UTC, Michiyamenotehifunana commented on code/modules/materials/material_sheets.dm
> +	spawn_tags = SPAWN_TAG_MATERIAL_RESOURCES_RARE  //Occulus edit: Re-adding platinum glass to spawn pools
Move this to the non-rare tag so science doesn't get cursed with a useless material at roundstart.

2021-03-07 00:21 UTC, Michiyamenotehifunana approved these changes
Looks good.

2021-03-07 00:22 UTC, merged