Removes DNA Switch Anomaly
Occulus-Server/Occulus-Eris pull request #354
Opened 2021-03-24 23:24 UTC by Mocha-Not-Latte

## About The Pull Request

non-modular removal of mutation anomaly that caused people to mutate.

## Why It's Good For The Game

No longer forces people to be something they don't wish to be! It also couldn't be protected against big ol heck.

## Changelog
```changelog
del: Removed mutation anomaly.
```

2021-03-25 00:02 UTC, Jamini requested changes
Kindly comment it out instead of removing it.
Thanks!

2021-03-25 00:09 UTC, Mocha-Not-Latte commented
> Kindly comment it out instead of removing it.
> Thanks!

Done

2021-03-26 18:21 UTC, zackerycodestoo approved these changes
All looks well, approved

2021-03-28 17:50 UTC, Jamini approved these changes

2021-03-28 17:50 UTC, merged