EMP mines and Snacks
Occulus-Server/Occulus-Eris pull request #377
Opened 2021-04-09 20:38 UTC by Jamini

## About The Pull Request

Adjusted EMP mine behavior
Added some flavor tags to junk foods

## Why It's Good For The Game

This makes mines less obnoxious to deal with.
Makes fufilling desires a bit easier

## Changelog
```changelog
fix: flash radius on explosions now does something!
tweak: The EMP landmine now only detonates if a mob walks on it, or it is touched
tweak: EMP mines can now be disabled by a multitool, like regular landmines.
tweak: picking up an active EMP mine triggers and disables it.
fix: De-russified some strings on regular landmines.
tweak: candy bars are now chocolate bars and fufill chocolate desires
tweak: chips now count as salty food
tweak: jerky no longer is poisonous and counts as meat food
tweak: raisins count as vegan food
tweak: Twinkies count as sweet food.
balance: Dr. Gibb only counts as sweet drink
```

2021-04-10 18:46 UTC, zackerycodestoo requested changes
As Cebutris said in coding discussions, could this be split into two pulls, one for mines and one for snacks? I know I've been a bit lenient about unrelated changes in the past

2021-04-14 01:25 UTC, Michiyamenotehifunana requested changes
typo

2021-04-14 01:25 UTC, Michiyamenotehifunana commented on code/game/objects/items/weapons/mine.dm
> +				SPAN_DANGER("[user] attempts to pick up the [src] only to hear a beep as it explodes in thier hands!"),//Occulus Edit: Russian grammar
thier

2021-04-14 02:52 UTC, Michiyamenotehifunana approved these changes
Good to go

2021-04-14 02:52 UTC, merged