Ports the payday meme alongside the associated vendor
Occulus-Server/Occulus-Eris pull request #574
Opened 2021-06-25 10:10 UTC by Michiyamenotehifunana

## About The Pull Request

<img width="271" alt="StrongDMM_FvH12OHWqk" src="https://user-images.githubusercontent.com/31995558/123409202-81159d00-d5e0-11eb-912f-154ca6724e3c.png">

<img width="84" alt="dreamseeker_E6bqMvPFs6" src="https://user-images.githubusercontent.com/31995558/123409307-9f7b9880-d5e0-11eb-9ba8-8ff979714d5a.png">

## Why It's Good For The Game

haha funny meme

## Changelog
```changelog Toriate
add: Ported payday meme from upstream together with the trash vendor
```

2021-06-25 12:32 UTC, Jamini commented on code/game/machinery/vending.dm
> +	product_slogans = "Discount guns for discount prices!;Also see our used ship line!;From the home of Challenge Pissing!"
"From the home of Challenge Pissing!""

2021-06-25 12:32 UTC, Jamini commented on code/game/machinery/vending.dm
> +					/obj/item/weapon/gun/projectile/automatic/ak47/fs = 3200,
Guns of this tier probably shouldn't be available from a vendor. We have a trade station for these.

2021-06-25 12:33 UTC, Jamini commented on code/game/machinery/vending.dm
> +	vendor_department = DEPARTMENT_CIVILIAN
Wrong department. This should be cargo.

2021-06-25 12:34 UTC, Jamini commented on maps/CEVEris/_CEV_Eris.dmm
> +/obj/machinery/vending/Billomat,
This shouldn't be there.

2021-06-25 12:35 UTC, Jamini requested changes
Lots of issues with the content of this PR.

2021-06-28 14:10 UTC, Michiyamenotehifunana commented
Vendor is no longer mapped in, now the new content has been moved to the ammo vendors.

2021-06-29 01:01 UTC, Michiyamenotehifunana commented
Now contraband in the ammo vendor

2021-06-29 18:40 UTC, Jamini approved these changes

2021-06-29 18:53 UTC, ShadzFen commented
I do really wish you'd give these PRs more effort. Anyone reading this PR will have no clue what's being added other than a bag, a payday mask and a vendor uwu

2021-06-29 18:53 UTC, merged