[DNM] Probrably stops the atuodoc from charging for autoscans
Occulus-Server/Occulus-Eris pull request #587
Opened 2021-07-03 08:50 UTC by Shadow-Quill

# **_DNM, untested webedit._**

## About The Pull Request

Adds a variable to the proc that checks if people can pay, which, if passed TRUE, doesn't try to charge the patient.
Helps stop peoples accounts from being drained just for using the autodoc (more than it would have already, that is.)

## Why It's Good For The Game

Hidden fees are bad.

## Changelog
```changelog
fix: Fixed the autodoc charging for a rescan after each operation is done.
```

2021-07-03 08:51 UTC, Shadow-Quill commented
this just in, I remember draft PRs are a thing.

2021-07-05 23:06 UTC, Shadow-Quill commented
Finally got around to testing this, it seems that it works.

2021-07-06 13:43 UTC, Jamini requested changes
Please mark changes to core files with the following comment at the end

//Occulus Edit

This helps us keep track of our changes if upstream modifies anything.

2021-07-11 22:11 UTC, Jamini approved these changes

2021-07-11 22:11 UTC, merged