Corrects ADMS disk teleporation and feedback
Occulus-Server/Occulus-Eris pull request #698
Opened 2021-09-05 22:50 UTC by Trilbyspaceclone

## About The Pull Request
ADMS now gives messages when a disk is not is-side well ejecting
Ejecting a disk now removes it form its lists preventing it form teleporting to were you deconstruct it

## Why It's Good For The Game
fix: Corrects the ADMS disk teleportation bug when decontructed
```

2021-09-05 22:54 UTC, Shadow-Quill requested changes

2021-09-05 22:54 UTC, Shadow-Quill commented on zzzz_modular_occulus/code/modules/maint_expeditions/ADMS.dm
> +	if(inserted_disk)
Above statement ensures there's a disk inserted, which means this if check can be deleted, I believe.

2021-09-05 22:59 UTC, Trilbyspaceclone commented on zzzz_modular_occulus/code/modules/maint_expeditions/ADMS.dm
> +	if(inserted_disk)
This check is in cases were its directly called by "call proc" to not get a runtime.

2021-09-05 23:08 UTC, Trilbyspaceclone commented on zzzz_modular_occulus/code/modules/maint_expeditions/ADMS.dm
> +	if(inserted_disk)
Ah, see what ya mean, corrected and when im done doing a quick conфermation check ill commit it <3

2021-09-06 00:46 UTC, Jamini approved these changes
Nothing ergious at first glance

2021-09-06 00:47 UTC, merged