Aegis gear updoot
Occulus-Server/Occulus-Eris pull request #791
Opened 2021-12-16 22:58 UTC by RadiantFlash7

## About The Pull Request
Cool new stuff:
New Aegis armor type called CAS Assault Harness, reduced armor for storage, placed in aegis prep
New aegis turtleneck, added to fashion closets
Cobalt Breaching hammer, used to smash down normal walls. Currently held and issuied by the sergeant.

## Why It's Good For The Game
Cause... fashion souls ss13 edition. And good features?

## Changelog
```changelog
add: New Aegis armor type called CAS Assault Harness
add: Aegis turtleneck
Add: CAS Breaching hammer
Mapchange: Adds objs to map!
```

2021-12-16 23:11 UTC, Shadow-Quill requested changes
CI's failing

2021-12-16 23:11 UTC, Shadow-Quill commented on zzzz_modular_occulus/code/game/objects/items/weapons/storage/belt.dm
> +		/obj/item/taperoll,
```suggestion
		/obj/item/taperoll
```

2021-12-16 23:12 UTC, Shadow-Quill commented
Also, `mapchange` is not a valid changelog tag

2021-12-16 23:44 UTC, RadiantFlash7 commented on zzzz_modular_occulus/code/game/objects/items/weapons/storage/belt.dm
> +		/obj/item/taperoll,
oops.

2021-12-17 00:01 UTC, RadiantFlash7 commented on zzzz_modular_occulus/code/game/objects/items/weapons/storage/belt.dm
> +		/obj/item/taperoll,
Fixed!

2021-12-17 05:24 UTC, RadiantFlash7 commented
I don't know why CI is failing

2021-12-17 06:44 UTC, Shadow-Quill commented on cev_eris.dme
> +#include "zzzz_modular_occulus\code\game\objects\items\weapons\tools\cobalthammer.dm"
CI is failing because of this addition, but this file isn't included in the PR.

2021-12-18 02:59 UTC, Shadow-Quill commented
You've got `/obj/item/weapon/tool/hammer/CAS` mapped in

2021-12-19 08:10 UTC, Shadow-Quill approved these changes

2021-12-20 02:56 UTC, merged