Sig cooking update
Occulus-Server/Occulus-Eris pull request #860
Opened 2022-03-31 23:54 UTC by SigDoesCode

## About The Pull Request
Adds meals! Meals are a new food item like custom salads intended to include main-course items like fries and steak, or eggs and waffles. To make a meal, put a food item on a plate. 

Meals can hold up to 4 items, and cannot hold other meals (get your recursive food elsewhere.) When you eat from a meal, you'll eat a bit of everything that's on the plate at a time. Meals can include custom salads too!
Here are the four stages of the meal sprite. The blobs take on the coloration of the food added, too!
![image](https://user-images.githubusercontent.com/84544997/161167992-c97c8f87-5f74-4f8a-872c-b797a54fbfb3.png)
An example of denying recursive meal creation.
![image](https://user-images.githubusercontent.com/84544997/161167875-373308ad-7e3a-49c3-baf5-1977ff92c2b5.png)

You can either make a sane meal, like this one...
![image](https://user-images.githubusercontent.com/84544997/161167710-6ad01d8c-5399-4391-b79a-835c355bdf7f.png)
or an insane meal, like this one.
![image](https://user-images.githubusercontent.com/84544997/161167760-d90a2b34-f404-42b3-8efb-61f0f8182aca.png)

They can also have condiments added to them. 

To allow meals to be created easier, Dinnerware vendors now include 5 plates. 
![image](https://user-images.githubusercontent.com/84544997/161167536-4848424f-b92f-4a77-ac18-7f1558c5c175.png)

## Why It's Good For The Game
Allows the kitchen to make more interesting stuff rather than just "here is bread, here is sandwich, here is burger."

## Changelog
```changelog
add: Meals! The kitchen is a bit more exciting now.
add: 5 plates should now be available in each Dinnerware.
```

2022-03-31 23:56 UTC, SigDoesCode commented
Oh, one last thing I forgot. If the name of the plate becomes too long, it becomes a "garbage plate" like this, as a reference to the garbage plate in Rochester, NY. 
![image](https://user-images.githubusercontent.com/84544997/161168736-f1eded7e-8131-4f7e-9c91-803a63664289.png)

2022-04-03 01:54 UTC, hex37 commented
I code for a different code base when I was handed this PR to look at today. Honest to god never knew Dreammaker treated their for loops that poorly. 

I gotta go redo all my list traversals now, fuck you, also thank you.

2022-04-13 18:04 UTC, Shadow-Quill requested changes

2022-04-13 18:04 UTC, Shadow-Quill commented on zzzz_modular_occulus/code/modules/cooking/meal.dm
> +		to_chat(user, "\red The [src] is too small to hold the [W]!")
I suggest using SPAN_WARNING here, in place of \red

2022-04-13 18:04 UTC, Shadow-Quill commented on zzzz_modular_occulus/code/modules/cooking/meal.dm
> +		update_taste(W)//Occulus Edit
Redundant comment :p

2022-04-13 19:57 UTC, Shadow-Quill commented
Need to remove `/weapon` from atom paths

2022-04-27 16:26 UTC, Shadow-Quill commented on zzzz_modular_occulus/code/modules/cooking/meal.dm
> +/obj/item/trash/plate/attackby(obj/item/weapon/W as obj, mob/user as mob)
```suggestion
/obj/item/trash/plate/attackby(obj/item/W as obj, mob/user as mob)
```

2022-04-27 16:32 UTC, Shadow-Quill requested changes
Still have `/weapon/`s laying around.

2022-04-27 17:35 UTC, Shadow-Quill commented
There are now merge conflicts

2022-04-27 19:26 UTC, SigDoesCode commented
> There are now merge conflicts

Where? How? I'm getting absolutely nothing from the CI checker. It tells me there's a map diff render conflict, I click details, and then it just says it's unmergeable.

2022-04-27 19:55 UTC, Shadow-Quill reviewed
Cleaning up whitespace

2022-04-27 19:55 UTC, Shadow-Quill commented on zzzz_modular_occulus/code/game/machinery/vending.dm
> +
```suggestion
```

2022-04-27 19:55 UTC, Shadow-Quill commented on zzzz_modular_occulus/code/game/machinery/vending.dm
> +
```suggestion
```

2022-04-28 19:13 UTC, Shadow-Quill approved these changes

2022-04-28 19:14 UTC, merged