Fixes Trays
Occulus-Server/Occulus-Eris pull request #867
Opened 2022-04-19 00:21 UTC by RadiantFlash7

## About The Pull Request
Fixes trays to actually pick things up, 
increases tray holding capacity
adds an attack cool down to trays so you can't murder someone in 5 seconds flat.

## Why It's Good For The Game
I demand a burger, fries, and a soda all fit on one tray properly.
Also being able to use trays is actually kinda nice.

## Changelog
```changelog
fix: fixes trays
```

2022-04-27 16:41 UTC, Shadow-Quill requested changes
Please also make the CL more descriptive of what you've done.

2022-04-27 16:41 UTC, Shadow-Quill commented on code/game/objects/items/weapons/trays.dm
> +	var/max_carry = 15
Need an edit comment

2022-04-27 16:41 UTC, Shadow-Quill commented on code/game/objects/items/weapons/trays.dm
> +							O.show_message(SPAN_DANGER("[I] flies off the tray!"), 1)
Ditto

2022-04-27 21:47 UTC, RadiantFlash7 commented
Comments made, Change logs improved

2022-04-28 19:16 UTC, Shadow-Quill approved these changes

2022-04-28 19:16 UTC, merged