Tools and RPEDs no longer can be blended by grinders.
Occulus-Server/Occulus-Eris pull request #899
Opened 2022-08-16 20:34 UTC by Jamini

## About The Pull Request

Prevents grinders from attempting to grind tools and RPEDs

## Why It's Good For The Game

No more accidentally recycling your welder.
No more "This probably won't blend" from trying to upgrade the parts in a grinder

## Changelog
```changelog
fix: Grinders now have a few sanity checks to prevent them from eating tools
```

2022-08-30 00:15 UTC, Jamini commented on code/modules/reagents/machinery/grinder.dm
> +	if (istype(I,/obj/item/gripper) && istype(I,/obj/item/storage/part_replacer))
If you don't explicitly ignore it, grinders treat RPEDs like an object you are trying to blend.

2022-08-30 02:08 UTC, Shadow-Quill requested changes

2022-08-30 02:08 UTC, Shadow-Quill commented on code/modules/reagents/machinery/grinder.dm
> +	if (istype(I,/obj/item/gripper) && istype(I,/obj/item/storage/part_replacer))
This check will never pass.
`I` would have to be both a gripper and an RPED.

2022-08-30 05:09 UTC, SigDoesCode commented on code/modules/reagents/machinery/grinder.dm
> +	if (istype(I,/obj/item/gripper) && istype(I,/obj/item/storage/part_replacer))
Replacing it with if (istype(I,/obj/item/gripper) || istype(I,/obj/item/storage/part_replacer)) would work, wouldn't it?

2022-08-30 13:11 UTC, Jamini commented
Fixed

2022-12-03 01:16 UTC, Shadow-Quill approved these changes

2022-12-03 01:16 UTC, merged