Fixes synthetics sending soulcrypts to the shadow realm
Occulus-Server/Occulus-Eris pull request #900
Opened 2022-08-16 20:56 UTC by Jamini

## About The Pull Request

The soulcrypt reader in NT cloning now drops the crypt on the floor instead of your hand.

## Why It's Good For The Game

This prevents synthetics from sending the core implant into the shadow realm. (an inaccessible part of the core implant reader)

## Changelog
```changelog
fix: Core implant readers no longer make soulcrypts inaccessible if a synthetic touches the device.
```

2022-08-16 21:03 UTC, Shadow-Quill requested changes
If you add a `put_in_hands` proc after the force move (may need an `!issilicon` check to prevent runtimes), you can have the implant still be put into human hands without losing it to the aether.

2022-08-16 22:30 UTC, Jamini commented
I don't really see the point in doing so. Originally I had made it more complex and check the type of the entity using the device, but ultimately KISS actually would apply here.

There just isn't a good reason to put this object directly into someone's hands, and it can cause other bugs (such as swapping hands too quickly on a humanmob causing the object to get lost. Which is currently an issue with chemistry equipment.)

2022-08-17 01:11 UTC, Shadow-Quill commented
It's quality of life, if anything, and the put in hands proc only has to be in a `if(!issilicon)` check

2022-08-17 15:10 UTC, Jamini commented
> Actually- I've just checked, and `put_in_hands()` also handles if it can't be put in the mob's hands (seemingly if an AI ejects it), and if it can't be put in the hands, it's just ejected onto the floor.
> 
> https://github.com/Occulus-Server/Occulus-Eris/blob/1f19288f7154109940ba298d5dee38b09c161295/code/modules/mob/inventory.dm#L39-L49

This suggested change causes soulcrypts to teleport to the AI core (or to a remote borg/drone if they aren't directly adjacent.)

2022-08-17 15:10 UTC, Jamini commented
![Screenshot_20220817_110813](https://user-images.githubusercontent.com/1775680/185176047-56fa8961-b2b4-424e-a887-2064552d0fc3.png)

2022-08-30 19:59 UTC, fludd12 approved these changes
Looks good, as long as you're alright slapping soulcrypts onto the floor. Which honestly isn't a huge problem.

2022-08-31 12:42 UTC, merged