Corporate Protection Officer: mind your CPO!
Occulus-Server/Occulus-Eris pull request #955
Opened 2023-03-10 11:50 UTC by Michiyamenotehifunana

## About The Pull Request
This PR adds a new alt title and equipment for Ensigns, the Corporate Protection Officer and their accompanying Guardian Tactical Armor. A corresponding uniform and beret is included.

![Aseprite_uSK1miyOAH](https://user-images.githubusercontent.com/31995558/224308266-f0154ad7-beb8-4a2f-bbfb-254ba107f3a9.png)

This allows ensign players to really lean into the bodyguard side of things, sticking close to their heads and protecting them.

![StrongDMM_Di2wHSmpx9](https://user-images.githubusercontent.com/31995558/224308318-5084fa9a-7c9f-4d39-9045-8788097d9af7.png) ![StrongDMM_HIrUUTZJvn](https://user-images.githubusercontent.com/31995558/224308325-b257a636-be29-4e0f-8844-421dc88f5d94.png)

The Guardian Tactical Armor set replaces the existing armor and helmet in the bridge armoury, meanwhile the beret and uniform are added to Ensign lockers. The armor set sacrifices energy armor for less encumbrance in general.

![gPuO5boIOc](https://user-images.githubusercontent.com/31995558/224308292-8c5897b3-a08b-404a-ba23-d4ecfe30aebe.png)

Update: The Guardian Tactical Armor vest now gets 40 melee armor, up from 30. Also the bridge armoury has been expanded with a Venger.
![StrongDMM_wrcgQD8Js0](https://user-images.githubusercontent.com/31995558/224469056-be667971-de7e-4fc1-bcaf-e87d967a3cb4.png)

Update: The above update has been reverted.

Update: The Guardian Tactical Vest now gets a new world sprite:
![Aseprite_Jy2FeOzM0w](https://user-images.githubusercontent.com/31995558/224519513-90c7b805-724a-40b4-b177-9bb84a34521d.png)

## Why It's Good For The Game

More content, more immersion for people who want to be bodyguards for heads.

## Changelog
```changelog
add: Corporate Protection Officer alt title for Ensigns and Guardian Tactical Armor set in bridge armoury.
```

2023-03-11 23:00 UTC, Jamini commented
1. The bridge should not have an AK. It already has two of the best guns in the game, and Aegis is supposed to handle external threats.
2. Please bring the CPO armor inline with other ballistic vests. Ideally it would be no more than a cosmetic resprite (maybe with additional style)
3. The item sprite (not the worn sprite, but the item sprite) should blook more compact/folded up. I can't tell it's armor at all from the screenshot.

2023-03-11 23:01 UTC, Jamini requested changes
1. The bridge should not get a rifle.
2. Please bring the armor on those vests inline with T1 security vests.
3. The item sprite could be made more compact and visually readable. Right now it... doesn't really look that good. The onmob sprites are fine.

2023-03-12 01:40 UTC, Michiyamenotehifunana commented
All changes implemented

2023-03-12 15:53 UTC, Jamini approved these changes

2023-03-12 15:53 UTC, merged