adds the Sword Scabbard holster
Occulus-Server/Occulus-Eris pull request #986
Opened 2023-05-19 03:18 UTC by Awesome4Real

## About The Pull Request

This PR mainly adds the Sword Scabbard, as an alternative to the uniform-attachable holsters. These scabbards can sheath swords, which can be holstered and unholstered with H in hotkey mode. This PR also makes holsters play a sound when holstering or unholstering weapons. These scabbards can be printed through mekhane's bioprinter.

## Why It's Good For The Game

This change allows swords to play a similar niche to pistols, being a quick-access backup weapon if you drop your main weapon.

## Changelog
```changelog
add: sword scabbards
add: sounds to holsters
```

2023-05-19 15:22 UTC, WeNeedMorePhoron requested changes

2023-05-19 15:22 UTC, WeNeedMorePhoron commented on code/modules/clothing/accessories/holster.dm
> +	if(istype(src, /obj/item/clothing/accessory/holster/sword)) //occy edit start
Nitpick, but can you change this to Occulus Edit so we have a standardized way of searching for Occulus Edited code?

2023-05-22 15:53 UTC, Shadow-Quill commented on code/modules/clothing/accessories/holster.dm
> +	if(istype(src, /obj/item/clothing/accessory/holster/sword)) //occy edit start
`Occulus edit` comments should be fully written out

2023-05-22 16:02 UTC, Shadow-Quill commented on code/modules/clothing/accessories/holster.dm
> +			to_chat(usr, SPAN_WARNING("You need your weapon equiped to holster it."))  //Occulus edit
```suggestion
			to_chat(usr, SPAN_WARNING("You need your weapon equipped to holster it."))  //Occulus edit
```

2023-05-22 16:13 UTC, Shadow-Quill approved these changes

2023-05-22 16:13 UTC, merged