Fix: Autodocs can remove shrapnel now.
Occulus-Server/Occulus-Eris pull request #990
Opened 2023-05-20 20:27 UTC by Awesome4Real

watch this break everything.

## About The Pull Request

So, the autodoc couldn't remove shrapnel because it wasn't using "locate" to find shrapnel in the limbs, like how surgery code does it, so it never found any.

"if(/obj/item/material/shard/shrapnel in external.implants)" VS "if(locate(/obj/item/material/shard/shrapnel) in external.implants)"

Implemented that and it worked as expected.

## Why It's Good For The Game

Unbuggening the autodoc seems useful for when there's no surgeons arounds.

## Changelog
```changelog
fix:autodoc can now remove shrapnel
```

2023-05-20 20:48 UTC, WeNeedMorePhoron commented on code/modules/surgery/autodoc.dm
> +				if(locate(/obj/item/material/shard/shrapnel) in external.implants) //occy edit
Nitpick - Occulus Edit please

2023-05-22 15:45 UTC, Shadow-Quill requested changes

2023-05-22 15:45 UTC, Shadow-Quill commented on code/modules/surgery/autodoc.dm
> +				if(locate(/obj/item/material/shard/shrapnel) in external.implants) //occy edit
It seems like this was implemented upstream at some point, so the edit comment isn't required, woo!
```suggestion
				if(locate(/obj/item/material/shard/shrapnel) in external.implants)
```

2023-05-24 15:39 UTC, Shadow-Quill approved these changes

2023-05-24 15:39 UTC, merged