Remove pretend weapon mechanic
Occulus-Server/Occulus-Eris pull request #992
Opened 2023-05-21 13:34 UTC by WeNeedMorePhoron

## About The Pull Request

## Why It's Good For The Game

## Changelog
```changelog
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
```

2023-05-21 14:38 UTC, WeNeedMorePhoron commented
Converted to draft, changing to an easier skill check with a better indicator.

2023-05-21 20:46 UTC, WeNeedMorePhoron commented
Updated PR with upstream code that make it a flat Biology * 4 percent to succeed. 
Added in clear data feature. 
Added in an indicator if your biology is above 10 that you've done it wrong. (Not that it is hard to tell if you codedive)

2023-05-22 15:42 UTC, Shadow-Quill requested changes

2023-05-22 15:42 UTC, Shadow-Quill commented on code/game/objects/items/weapons/autopsy.dm
> +		to_chat(user, SPAN_WARNING("You got a feeling you are not doing this right, maybe you should clear the data and try again"))
```suggestion
		to_chat(user, SPAN_WARNING("You got a feeling you are not doing this right, maybe you should clear the data and try again."))
```

2023-05-22 15:42 UTC, Shadow-Quill commented on code/game/objects/items/weapons/autopsy.dm
> +		to_chat(usr, "You must be conscious to do that!")
```suggestion
		to_chat(usr, SPAN_NOTICE("You must be conscious to do that!"))
```

2023-05-22 16:13 UTC, Shadow-Quill approved these changes

2023-05-22 16:13 UTC, merged