Upstream Grenades: HESH Rocket, Buffed Fragmentation, Pipebomb, WP & Fix
Occulus-Server/Occulus-Eris pull request #997
Opened 2023-05-23 14:06 UTC by WeNeedMorePhoron

## About The Pull Request
- Port in most of #7850 Upstream, White Phosphorus Grenades (mispelled in code)
- Port in most of #7025 - Adding HESH Rocket, Buffed Fragmentation, Stinger Grenades. Modular Occulus Stinger code & sprites have been replaced with theirs with name override. Double check if the names I've made up for the unused FTU grenade is fine. (They added it but haven't used it upstream yet)
- Port in #7187 - Added blast radius to frag grenades
- Ported in the three pipebombs PRs. Forgot name. It can be crafted in crafting menu.

**ORIGINAL CHANGES**
- Due to WP Grenades being extremely underwhelming (taking 3 - 6 minutes to knock someone down), I've buffed fire stack by roughly 2x by making them cause additional burn damage and make it less ignorable. Getting full fire stacked without clothes should knock you down in around 1 minute or so.
- WP Grenades are accessible to traitor through uplink (Unused except in centcomm upstream)
- Fixed a server crash / duping issue with grenade launcher. This will be PRed upstream if I am able to replicate it upstream.

## Why It's Good For The Game

## Changelog
```changelog
add: Craftable Pipebomb made with plasma cells 
add: HESH Rockets. RPG-7 package starts with 4 out of 12 rockets being HESH. HESH rocket have worse blast but send a lot of fragments to the other side of a room.
add: White phosphorus grenades, accessible to traitor for now.
tweak: Normal HE Rocket nerfed a bit, upstream parity. Still kill with a direct hit. 
tweak: Stinger Grenades sprite changed to match upstream, fragmentation grenades now cause a 2 tiles small blast around itself. 
tweak: Grenades dropping on someone from above should now bonk off someone's head.
tweak: Grenade fragments now ricochet making them much deadlier, especially in small room.
tweak: Fire stacks are much deadlier, approximately by 2x, making being on fire less ignorable.
fix: A crash that can happen with grenade launcher launched grenade.
```

2023-05-23 14:07 UTC, WeNeedMorePhoron commented
After writing out the PR I realized I forgot to check the bonking feature (Because that require a multikey). Please hold off on merging until I confirm it work.

2023-05-23 23:48 UTC, WeNeedMorePhoron commented on code/modules/projectiles/projectile.dm
> +		if(!bumped && !QDELETED(original) && !isturf(original))
upstream change

2023-05-23 23:48 UTC, WeNeedMorePhoron commented on code/modules/projectiles/projectile.dm
> +	while(!QDELETED(src) && src.loc)
loop was utterly cursed so i changed it

2023-05-23 23:48 UTC, WeNeedMorePhoron commented
Ready for review

2023-05-24 18:07 UTC, Jamini requested changes
Please test all of these and give us rough damage values.

We had to nerf several explosions from Eris because they were onetaps.

2023-05-24 19:00 UTC, Shadow-Quill reviewed
No complaints code-wise.

2023-05-24 19:27 UTC, Jamini approved these changes

2023-05-24 19:27 UTC, merged